### ISSUE TITLE
Add endpoint to retrieve template schema for a given version ID

### ISSUE THREAD

**Issue by tudorgroza** [EBISPOT/gwas-template-services#7] opened 2019-07-12 14:50 UTC
* Proposed endpoint: `GET /v1/template-schema/{version}`
 * Proposed response:
```
	{
	  "version": "DgucZJ6zHY",				// (M) Same as 'version' above
	  "studySheet": {						// (M)
	    "triggerRow": "Y2s2Q5KEet",			// (M) Validator needs this to know where to start
	    "studyTagColumnName": "4CrMztP6Mu",	// (M) Needed to map study tags across sheets
	    "columns": [
	      {
	        "columnName": "gDzUJbHkCv",		// (M) Column identifier
	        "columnHeading": "2scjRRO8iU",	// (M) Column heading to be used to produce human readable errors
	        "baseType": "HikXvBswqn",		// (M) STRING | NUMERIC
	        "required": true,				// (M) Required status for the column
	        "pattern": "f86ugRHI7d",		// (O) Validation pattern
	        "lowerBound": 10,				// (O) Validation pattern
	        "upperBound": 10,				// (O) Validation pattern
	        "acceptedValues": [				// (O) Validation pattern
	          "8fK0R8hUUj",
	          "YTIUmqRj6A",
	          "8QPBb1Krnf"
	        ]
	      }
	    ]
	  },
	  "templateSheets": [
	    {
	      "triggerRow": "aBPIuY2UuW",
	      "studyTagColumnName": "8mKaUuGjJg",
	      "columns": [
	        {
	          "columnName": "xHpT0NxUrE",
	          "columnHeading": "6pmiJL0yBZ",
	          "baseType": "bASZXMklud",
	          "required": true,
	          "pattern": "vYEFTRqo0D",
	          "lowerBound": 10,
	          "upperBound": 10,
	          "acceptedValues": [
	            "doqDntA2bl",
	            "pdl2ocGQxa",
	            "4BuLDYDHyB"
	          ],
	          "summaryStatsSchema": {						// (O) Only if needed
	            "summaryStatsFileColumn": "0Am7SwKntD",		// (M) If object present
	            "summaryStatsMD5Column": "5yB2U9JuyR",		// (M) If object present
	            "summaryStatsAssemblyColumn": "A9d58l5eIB"	// (O)
	          }
	        }
	      ]
	    }
	  ]
	}
```
 * Note:
   * (M) - denotes `Mandatory` | (O) - denotes `Optional`
   * The `studySheet` field - while having the same structure as the other ones under `templateSheets` - needs to be separated in order to enable detection of orphan associations and samples
   * `summaryStatsSchema` can be placed in any of the sheets.

**Comment by DSuveges** [comment] 2019-07-14 21:06
OK, for sure, I can support versioning of the schemas. That's fine, and I have already thought a lot about that. (What's the `v1` in the proposed address by the way?)

The proposed response is not complete and I think misses the point that column name, mandatory flag etc is defined per column not per sheet. Anyway, I'll sort that out. Also, am I right, that you are expecting the schemas for all sheets in one JSON?

An other question: pattern, lowerBound, upperBound, acceptedValues are not defined for all columns (eg. for a string field, there's no point talking about upper or lower bounds), do you expect these fields to be presented for all columns or only for those were they are defined? 

I'll compile a more realistic response, send over to you on Monday, if you like it, the implementation will be ready on Tuesday, or Wednesday the latest.

For the documentation of the endpoints, you can go to `http://snoopy:9000/` and click on the "default namespace" to see all the endpoints. By clicking the endpoints you will find a brief description and usage with parameters etc.

**Comment by tudorgroza** [comment] 2019-07-15 00:32
@DSuveges - thanks for this.
Please note the following:
 - Using `{version}` is the easiest way we can cater at this point for multiple versions and for you to 'hide' a piece of information in the generated template - which I can pick up and use for validation. The alternative is to encode everything in the Spreadsheet
 - `/v1` is a placeholder for future versions of the API. It's standard practice to version the API
 - w.r.t. the mandatory flag, etc - you are correct - the missing `List` is my mistake - have corrected it above.
 - w.r.t. `lowerBound`, etc - as per my notation above `(O)` - they are optional
 - w.r.t. the existing endpoints - unfortunately, I need the data in a specific format to be able to process it and feed it to the validator. Hope this is fine with you.

**Comment by DSuveges** [comment] 2019-07-15 08:49
Thanks. Now everything is clear. I'll start working on the implementation.

**Comment by tudorgroza** [comment] 2019-07-15 08:57
Thank you, Sir!

**Comment by DSuveges** [comment] 2019-07-15 15:24
Branch addressing the issue is merged:  #8 
Deployed to snoopy. Please take a look, let me know if something is off.

**Comment by tudorgroza** [comment] 2019-07-16 10:04
@DSuveges - what versions do you currently support?

**Comment by tudorgroza** [comment] 2019-07-16 11:52
@DSuveges - found the version list.
Can I please ask you to do one change?
Can you please set `studyTagColumnName` to the value corresponding to the field `columnName` in `columns`? For example `study_tag` in the current implementation.

Thank you!

PS: Given a template generated by your generator - where will I find the version number hidden?

**Comment by DSuveges** [comment] 2019-07-16 12:05
`Can you please set studyTagColumnName to the value corresponding to the field columnName in columns? For example study_tag in the current implementation.`
Sure, I'll do it.

`Given a template generated by your generator - where will I find the version number hidden?`
I don't know yet, I hope I can came up with a solution today or tomorrow the latest.

**Comment by DSuveges** [comment] 2019-07-16 12:41
Now there a new branch deployed to snoopy that generates spreadsheets where the schema version is added to the excel metadata. Please try:`http://snoopy:9000/template_download_test`

The version is stored in the comments section: `schemaVersion=1.0` in the current version.

![GitHub Logo](https://i.imgur.com/Vs4SMct.png)

**Comment by tudorgroza** [comment] 2019-07-16 12:46
Perfect! Thank you!
I'll try to get it from there.

**Comment by DSuveges** [comment] 2019-07-16 12:50
It seems good, although I'm a bit worried how difficult it is to extract this information from the file... please let me know if you have trouble with that. If you have problem getting the template, here's an updated version: `http://bit.ly/update_template`

**Comment by tudorgroza** [comment] 2019-07-16 13:06
I was able to get it out. All good. Thanks a lot!

**Comment by DSuveges** [comment] 2019-07-16 13:07
Good. Thanks. Do you think we can close the issue?

**Comment by tudorgroza** [comment] 2019-07-16 13:07
Yep. Thank you!

**Closed** 2019-07-16 13:13 UTC
Labels: TemplateService, enhancement
